@startuml
title Warmhouse Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Пользователь, который использует систему для установки и проверки температуры")
Person(admin, "Administrator", "Администратор, управляющий системой")
Person(serviceman, "Service man", "Специалист, устанавливающий и регистрирующий датчики")
System(WarmhouseSystem, "Warmhouse System", "Система управления удаленными датчиками температуры")

System_Ext(sensor, "Умный датчик", "Датчики температуры, которыми управляет система")
'System_Ext(bank, "Bank System", "External bank for processing payments")

Rel(user, WarmhouseSystem, "Использует систему")
Rel(admin,WarmhouseSystem,"Управляет системой")
Rel(serviceman, WarmhouseSystem,"Регистрирует датчики")
Rel(sensor, WarmhouseSystem,"Передает показания")
Rel(WarmhouseSystem, sensor, "Привязывает датчик в помещении")
@enduml